# Generated by Django 3.2.14 on 2022-07-24 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movies',
            name='img',
            field=models.ImageField(default='abab', upload_to='image'),
            preserve_default=False,
        ),
    ]
